---
title: "Respiration in Old vs Young Bean Sprouts"
output: html_document
---

```{r}
library(dplyr)
library(tidyr)
library(ggplot2)
sprouts <- read.csv("../datasets/respiration.csv")
str(sprouts)
sprouts <- tbl_df(sprouts)
sprouts
sprouts <- gather(sprouts, "minutes", "distance", 4:7)
sprouts$minutes <- recode(sprouts$minutes, "X5.min" = 5, "X10.min" = 10,
       "X15.min" = 15, "X20.min" = 20)

plot_data <- sprouts %>% group_by(minutes, Age) %>% 
  summarize(avg_dist = mean(distance, na.rm = T), 
            se_dist = sd(distance, na.rm = T)/sqrt(sum(!is.na(distance))))

```

```{r}
plot_data

pd <- position_dodge(0)
ggplot(plot_data, aes(x=minutes, y = avg_dist, color = Age, group = Age)) +
  geom_errorbar(aes(ymin=avg_dist-se_dist, ymax=avg_dist+se_dist), 
                width=.1, position=pd) + 
  geom_point(position=pd) +
  ylab("distance (mm)") +
  # geom_line() + 
  expand_limits(x = 0, y = 0)
```

```{r}
model1 <- lm(distance ~ minutes + Age + minutes * Age, data = sprouts)
summary(model1)
```

